Modules/CodeEduUser/Http/routes.php
<?php

Route::group(['as' => 'codeeduuser.','middleware'=> ['auth', config('codeeduuser.middleware.isVerified')]], function(){


	Route::group(['prefix' => 'admin', 'middleware' => 'can:user-admin'], function(){

		Route::resource('users', 'UsersController');
		Route::resource('roles', 'RolesController');
		Route::get('roles/{role}/permissions', 'RolesController@editPermission')->name('roles.permissions.edit');
		Route::put('roles/{role}/permissions', 'RolesController@updatePermission')->name('roles.permissions.update');

	});

	Route::get('users/settings', 'UserSettingsController@edit')->name('user_settings.edit');
	Route::put('users/settings', 'UserSettingsController@update')->name('user_settings.update');

	Route::get('email-verification/error', 'UserConfirmationController@getVerificationError')->name('email-verification.error');
	Route::get('email-verification/check/{token}', 'UserConfirmationController@getVerification')->name('email-verification.check');

});

Modules/CodeEduUser/Models/Role.php
<?php

namespace CodeEduUser\Models;

use Illuminate\Database\Eloquent\Model;
use Bootstrapper\Interfaces\TableInterface;

class Role extends Model implements TableInterface
{
    protected $fillable = [
    	'name', 'description'
    ];

    public function permissions()
    {
    	return $this->belongsToMany(Permission::class);
    }

    public function users()
    {
    	return $this->belongsToMany(User::class);	
    }

    public function getTableHeaders()
    {
        return ['#', 'Nome', 'Descrição'];
    }

    public function getValueForHeader($header)
    {
        switch ($header) {
            case '#':
                return $this->id;
            
            case 'Nome':
                return $this->name;
            case 'Descrição':
                return $this->description;    
            
        }
    }
}

Modules/CodeEduUser/Http/Controllers/RolesController.php
<?php

namespace CodeEduUser\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use CodeEduUser\Http\Requests\RoleDeleteRequest;
use CodeEduUser\Http\Requests\RoleRequest;
use CodeEduUser\Repositories\RoleRepository;

class RolesController extends Controller
{
    
    private $repository;

    public function __construct(RoleRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {   
        $roles = $this->repository->paginate(10);

        return view('codeeduuser::roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('codeeduuser::roles.create');
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(RoleRequest $request)
    {
        $this->repository->create($request->all());
        // pegando a url anterior da requisição para redirecionar para a mesma    
        $url = $request->get('redirect_to', route('codeeduuser.roles.index'));
        // criando mensagens    
        $request->session()->flash('message', 'Perfil de usuário cadastrado com sucesso!');

        return redirect()->to($url);
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit($id)
    {
        $role = $this->repository->find($id);

        return view('codeeduuser::roles.edit', compact('role'));
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(RoleRequest $request, $id)
    {
        $this->repository->update($request->all(), $id);
        // pegando a url anterior da requisição para redirecionar para a mesma
        $url = $request->get('redirect_to', route('codeeduuser.roles.index'));

        $request->session()->flash('message', 'Perfil de usuário alterado com sucesso!');

        return redirect()->to($url);
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy($id)
    {
        try{

            $this->repository->delete($id);

            \Session::flash('message', 'Perfil de usuário excluído com sucesso!');
        
        }catch(QueryException $ex) {

            \Session::flash('message', 'Perfil de usuário não pode ser excluído. Ele está relacionado com outros registros.');

        }
        
        return redirect()->to(\URL::previous());
    }
}

Modules/CodeEduUser/resources/views/roles/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<h3>Novo Perfil de Usuário</h3>
			{!! Form::open(['route' => 'codeeduuser.roles.store', 'class' => 'form', 'method' => 'POST']) !!}
			{!! Form::hidden('redirect_to', URL::previous()) !!}
				<!-- nome -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup('name', $errors) !!}
						{!! Form::label('name', 'Nome:', ['class'=>'control-label']) !!}
						{!! Form::text('name', null, ['class' => 'form-control']) !!}
						{!! Form::error('name', $errors) !!}
					{!! Html::closeDiv() !!}
				{!! Html::closeDiv() !!}
				<!-- email -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup('description', $errors) !!}
						{!! Form::label('description', 'Descrição:', ['class'=>'control-label']) !!}
						{!! Form::text('description', null, ['class' => 'form-control']) !!}
						{!! Form::error('description', $errors) !!}
					{!! Html::closeDiv() !!}
				{!! Html::closeDiv() !!}
				<!-- botao -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup('name', $errors) !!}
						{!! Button::primary('Criar perfil')->submit() !!}
					{!!Html::openFormGroup('name', $errors) !!}
				{!! Html::closeDiv() !!}
			{!! Form::close() !!}
		</div>	
	</div>	
@endsection

Modules/CodeEduUser/resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<h3>Editar Perfil de Usuário</h3>
			{!! Form::model($role, ['route' => ['codeeduuser.roles.update', 'role'=> $role->id], 'class' => 'form', 'method' => 'PUT']) !!}
			{!! Form::hidden('redirect_to', URL::previous()) !!}
				<!-- nome -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup('name', $errors) !!}
						{!! Form::label('name', 'Nome:', ['class'=>'control-label']) !!}
						{!! Form::text('name', null, ['class' => 'form-control']) !!}
						{!! Form::error('name', $errors) !!}
					{!! Html::closeDiv() !!}
				{!! Html::closeDiv() !!}
				<!-- Email -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup('description', $errors) !!}
						{!! Form::label('description', 'Descrição:', ['class'=>'control-label']) !!}
						{!! Form::text('description', null, ['class' => 'form-control']) !!}
						{!! Form::error('description', $errors) !!}
					{!! Html::closeDiv() !!}
				{!! Html::closeDiv() !!}
				<!-- botao -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup() !!}
						{!! Button::primary('Salvar perfil')->submit() !!}
					{!!Html::openFormGroup() !!}
				{!! Html::closeDiv() !!}
			{!! Form::close() !!}
		</div>	
	</div>	
@endsection

Modules/CodeEduUser/resources/views/roles/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="col-sm-4">
			<h1>Papéis de usuários</h1><br>
		</div>
		<div class="col-sm-offset-6 col-sm-2">
			{!! Button::primary('Novo papel de usuário')->asLinkTo(route('codeeduuser.roles.create')) !!}
		</div>
		<!-- FORMA MAIS PRÁTICA DE FAZER TABELA USANDO O BOOTSTRAPPER -->
		{!! 
			Table::withContents($roles->items())->striped()
				->callback('Ações', function($field, $role){
					$linkEdit = route('codeeduuser.roles.edit', ['role' => $role->id]);
					$linkDestroy = route('codeeduuser.roles.destroy', ['role' => $role->id]);
					$linkEditPermission = route('codeeduuser.roles.permissions.edit', ['role' => $role->id]);
					$deleteForm = "delete-form-{$role->id}";
					$form = Form::open(['route' =>
								['codeeduuser.roles.destroy', 'role' => $role->id],
								'method' => 'DELETE', 'id' => $deleteForm, 'style' => 'display:none']).
								Form::close();
					$anchorDestroy = Button::danger('Deletar')->asLinkTo($linkDestroy)->addAttributes([
										'onclick' => "event.preventDefault();document.getElementById(\"{$deleteForm}\").submit();"
									]);			
					return "<ul class=\"list-inline\">".
								"<li>".Button::primary('Editar')->asLinkTo($linkEdit)."</li>".
								"<li>|</li>".
								"<li>".$anchorDestroy."</li>".
								"<li>|</li>".
								"<li>".Button::success('Permissões')->asLinkTo($linkEditPermission)."</li>".
							"</ul>".
							$form;
				})
		!!}
		<!-- PAGINAÇÃO -->
		{{$roles->links()}}
	</div>
@endsection