Modules/CodeEduUser/Http/routes.php
<?php

Route::group(['as' => 'codeeduuser.','middleware'=> ['auth', config('codeeduuser.middleware.isVerified')]], function(){


	Route::group(['prefix' => 'admin', 'middleware' => 'can:user-admin'], function(){

		Route::resource('users', 'UsersController');
		Route::resource('roles', 'RolesController');
		Route::get('roles/{role}/permissions', 'RolesController@editPermission')->name('roles.permissions.edit');
		Route::put('roles/{role}/permissions', 'RolesController@updatePermission')->name('roles.permissions.update');

	});

	Route::get('users/settings', 'UserSettingsController@edit')->name('user_settings.edit');
	Route::put('users/settings', 'UserSettingsController@update')->name('user_settings.update');

	Route::get('email-verification/error', 'UserConfirmationController@getVerificationError')->name('email-verification.error');
	Route::get('email-verification/check/{token}', 'UserConfirmationController@getVerification')->name('email-verification.check');

});

Modules/CodeEduUser/Models/User.php
<?php

namespace CodeEduUser\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Bootstrapper\Interfaces\TableInterface;
use Illuminate\Database\Eloquent\SoftDeletes;
use Collective\Html\Eloquent\FormAccessible;

class User extends Authenticatable implements TableInterface
{
    use Notifiable;

    use SoftDeletes;

    use FormAccessible;

    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    public function formRolesAttribute()
    {
        return $this->roles->pluck('id')->all();
    }

    public static function generatePassword($password = null)
    {
        return !$password ? bcrypt(str_random(8)) : bcrypt($password);
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getTableHeaders()
    {
        return ['#', 'Nome', 'E-mail', 'Roles'];
    }

    public function getValueForHeader($header)
    {
        switch ($header) {
            case '#':
                return $this->id;
            case 'Nome':
                return $this->name;
            case 'E-mail':
                return $this->email;
            case 'Roles':
                return $this->roles->implode('name', ' | ');    

        }
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class);   
    }

    // @param permitir uma colection ou string
    public function hasRole($role)
    {
        return is_string($role) ? 
            $this->roles->contains('name', $role) :
            (boolean) $role->intersect($this->roles)->count();
            //fazendo uma interseção entre as roles 
    }

    public function isAdmin()
    {
        return $this->hasRole(config('codeeduuser.acl.role_admin'));
    }
}

Modules/CodeEduUser/Http/Controllers/UsersController.php
<?php

namespace CodeEduUser\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use CodeEduUser\Http\Requests\UserRequest;
use CodeEduUser\Http\Requests\UserDeleteRequest;
use CodeEduUser\Repositories\UserRepository;
use CodeEduUser\Repositories\RoleRepository;
use CodeEduUser\Annotations\Mapping\Controller as ControllerAnnotation;
use CodeEduUser\Annotations\Mapping\Action as ActionAnnotation;

/**
*  @ControllerAnnotation(name="users-admin", description="Administração")
*/
class UsersController extends Controller
{

     /**
     * @var UserRepository
     */
    protected $repository;

    /**
    * @var Role Repository
    */
    protected $roleRepository;

    public function __construct(UserRepository $repository, RoleRepository $roleRepository)
    {
        $this->repository = $repository;

        $this->roleRepository = $roleRepository;

    }


    /**
     * Display a listing of the resource.
     * @ActionAnnotation(name="List", description="Ver listagem de usuários")
     * @return Response
     */
    public function index()
    {
        $users = $this->repository->paginate(5);

        return view('codeeduuser::users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $roles = $this->roleRepository->all()->pluck('name', 'id');

        return view('codeeduuser::users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     * @param  UserRequest $request
     * @return Response
     */
    public function store(UserRequest $request)
    {   
        $this->repository->create($request->all());
        // pegando a url anterior da requisição para redirecionar para a mesma    
        $url = $request->get('redirect_to', route('codeeduuser.users.index'));
        // criando mensagens    
        $request->session()->flash('message', 'Usuário cadastrado com sucesso!');

        return redirect()->to($url);
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit($id)
    {
        $user = $this->repository->find($id);

        $roles = $this->roleRepository->all()->pluck('name', 'id');

        return view('codeeduuser::users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(UserRequest $request, $id)
    {
        $data = $request->except(['password']);

        $this->repository->update($data, $id);
        // pegando a url anterior da requisição para redirecionar para a mesma
        $url = $request->get('redirect_to', route('codeeduuser.users.index'));

        $request->session()->flash('message', 'Usuário alterado com sucesso!');

        return redirect()->to($url);
    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy(UserDeleteRequest $request, $id)
    {
        $this->repository->delete($id);

        \Session::flash('message', 'Usuário excluído com sucesso!');
        
        return redirect()->to(\URL::previous());
    }
}

Modules/CodeEduUser/resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<h3>Novo Usuário</h3>
			{!! Form::open(['route' => 'codeeduuser.users.store', 'class' => 'form', 'method' => 'POST']) !!}
			{!! Form::hidden('redirect_to', URL::previous()) !!}
				<!-- nome -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup('name', $errors) !!}
						{!! Form::label('name', 'Nome:', ['class'=>'control-label']) !!}
						{!! Form::text('name', null, ['class' => 'form-control']) !!}
						{!! Form::error('name', $errors) !!}
					{!! Html::closeDiv() !!}
				{!! Html::closeDiv() !!}
				<!-- email -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup('email', $errors) !!}
						{!! Form::label('email', 'E-mail:', ['class'=>'control-label']) !!}
						{!! Form::text('email', null, ['class' => 'form-control']) !!}
						{!! Form::error('email', $errors) !!}
					{!! Html::closeDiv() !!}
				{!! Html::closeDiv() !!}
				<!--roles -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup(['roles', 'roles.*'], $errors) !!}
						{!! Form::label('roles[]', 'Papel de usuário:', ['class'=>'control-label']) !!}
						{!! Form::select('roles[]', $roles, null, ['class' => 'form-control', 'multiple' => true]) !!}
						{!! Form::error('roles.*', $errors) !!}
						{!! Form::error('roles', $errors) !!}
					{!! Html::closeDiv() !!}
				{!! Html::closeDiv() !!}
				<!-- botao -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup('name', $errors) !!}
						{!! Button::primary('Criar usuário')->submit() !!}
					{!!Html::openFormGroup('name', $errors) !!}
				{!! Html::closeDiv() !!}
			{!! Form::close() !!}
		</div>	
	</div>	
@endsection

Modules/CodeEduUser/resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<h3>Editar Usuário</h3>
			{!! Form::model($user, ['route' => ['codeeduuser.users.update', 'user'=> $user->id], 'class' => 'form', 'method' => 'PUT']) !!}
			{!! Form::hidden('redirect_to', URL::previous()) !!}
				<!-- nome -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup('name', $errors) !!}
						{!! Form::label('name', 'Nome:', ['class'=>'control-label']) !!}
						{!! Form::text('name', null, ['class' => 'form-control']) !!}
						{!! Form::error('name', $errors) !!}
					{!! Html::closeDiv() !!}
				{!! Html::closeDiv() !!}
				<!-- Email -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup('email', $errors) !!}
						{!! Form::label('email', 'E-mail:', ['class'=>'control-label']) !!}
						{!! Form::text('email', null, ['class' => 'form-control']) !!}
						{!! Form::error('email', $errors) !!}
					{!! Html::closeDiv() !!}
				{!! Html::closeDiv() !!}
				<!--roles -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup('roles.*', $errors) !!}
						{!! Form::label('roles[]', 'Papel de usuário:', ['class'=>'control-label']) !!}
						{!! Form::select('roles[]', $roles, null, ['class' => 'form-control', 'multiple' => true]) !!}
						{!! Form::error('roles.*', $errors) !!}
					{!! Html::closeDiv() !!}
				{!! Html::closeDiv() !!}
				<!-- botao -->
				{!! Html::openLine() !!}
					{!!Html::openFormGroup('name', $errors) !!}
						{!! Button::primary('Salvar usuário')->submit() !!}
					{!!Html::openFormGroup('name', $errors) !!}
				{!! Html::closeDiv() !!}
			{!! Form::close() !!}
		</div>	
	</div>	
@endsection

Modules/CodeEduUser/resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="col-sm-4">
			<h1>Lista da Usuários</h1><br>
		</div>
		<div class="col-sm-offset-6 col-sm-2">
			{!! Button::primary('Novo Usuário')->asLinkTo(route('codeeduuser.users.create')) !!}
		</div>
		<!-- FORMA MAIS PRÁTICA DE FAZER TABELA USANDO O BOOTSTRAPPER -->
		{!! 
			Table::withContents($users->items())->striped()
				->callback('Ações', function($field, $user){
					$linkEdit = route('codeeduuser.users.edit', ['user' => $user->id]);
					$linkDestroy = route('codeeduuser.users.destroy', ['user' => $user->id]);
					$deleteForm = "delete-form-{$user->id}";
					$form = Form::open(['route' =>
								['codeeduuser.users.destroy', 'user' => $user->id],
								'method' => 'DELETE', 'id' => $deleteForm, 'style' => 'display:none']).
								Form::close();
					$anchorDestroy = Button::danger('Deletar')->asLinkTo($linkDestroy)->addAttributes([
										'onclick' => "event.preventDefault();document.getElementById(\"{$deleteForm}\").submit();"
									]);
					if($user->id == \Auth::user()->id) {
						$anchorDestroy->disable();
					}
											
					return "<ul class=\"list-inline\">".
								"<li>".Button::primary('Editar')->asLinkTo($linkEdit)."</li>".
								"<li>|</li>".
								"<li>".$anchorDestroy."</li>".
							"</ul>".
							$form;
				})
		!!}
		<!-- PAGINAÇÃO -->
		{{$users->links()}}
	</div>
@endsection